using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class apitest_divineapi_sample_2 : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {

    }


    protected void btnShowPlanets_Click(object sender, EventArgs e)
    {
        // Paste your full JSON response here
        string sampleJson = @"{
    ""success"": 1,
    ""data"": {
        ""p1"": {
            ""date"": ""1990-06-24"",
            ""time"": ""14:30:00"",
            ""latitude"": 28.6139,
            ""longitude"": 77.209,
            ""timezone"": 5.5,
            ""planets"": [
                {
                    ""name"": ""Sun"",
                    ""name_lan"": ""Sun"",
                    ""full_degree"": ""68.8754426"",
                    ""speed"": ""0.9542966"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""8:52:31"",
                    ""sign"": ""Gemini"",
                    ""sign_no"": 3,
                    ""rashi_lord"": ""Mercury"",
                    ""nakshatra"": ""Aradra"",
                    ""nakshatra_pada"": 1,
                    ""nakshatra_no"": 6,
                    ""nakshatra_lord"": ""Rahu"",
                    ""sub_lord"": ""Jupiter"",
                    ""awastha"": ""Kumar"",
                    ""karakamsha"": ""Putra"",
                    ""house"": 9,
                    ""type"": ""malefic"",
                    ""lord_of"": ""Eleventh House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Sun.png""
                },
                {
                    ""name"": ""Moon"",
                    ""name_lan"": ""Moon"",
                    ""full_degree"": ""90.6531177"",
                    ""speed"": ""14.4040122"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""0:39:11"",
                    ""sign"": ""Cancer"",
                    ""sign_no"": 4,
                    ""rashi_lord"": ""Moon"",
                    ""nakshatra"": ""Punarvasu"",
                    ""nakshatra_pada"": 4,
                    ""nakshatra_no"": 7,
                    ""nakshatra_lord"": ""Jupiter"",
                    ""sub_lord"": ""Mars"",
                    ""awastha"": ""Mrityu"",
                    ""karakamsha"": ""Dara"",
                    ""house"": 10,
                    ""type"": ""neutral"",
                    ""lord_of"": ""Tenth House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Moon.png""
                },
                {
                    ""name"": ""Mercury"",
                    ""name_lan"": ""Mercury"",
                    ""full_degree"": ""58.8783221"",
                    ""speed"": ""2.0735371"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""true"",
                    ""longitude"": ""28:52:41"",
                    ""sign"": ""Taurus"",
                    ""sign_no"": 2,
                    ""rashi_lord"": ""Venus"",
                    ""nakshatra"": ""Mrigashirsha"",
                    ""nakshatra_pada"": 2,
                    ""nakshatra_no"": 5,
                    ""nakshatra_lord"": ""Mars"",
                    ""sub_lord"": ""Saturn"",
                    ""awastha"": ""Baal"",
                    ""karakamsha"": ""Amatya"",
                    ""house"": 8,
                    ""type"": ""benefic"",
                    ""lord_of"": ""Ninth,Twelfth House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Mercury.png""
                },
                {
                    ""name"": ""Venus"",
                    ""name_lan"": ""Venus"",
                    ""full_degree"": ""35.5208643"",
                    ""speed"": ""1.1833104"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""5:31:15"",
                    ""sign"": ""Taurus"",
                    ""sign_no"": 2,
                    ""rashi_lord"": ""Venus"",
                    ""nakshatra"": ""Krittika"",
                    ""nakshatra_pada"": 3,
                    ""nakshatra_no"": 3,
                    ""nakshatra_lord"": ""Sun"",
                    ""sub_lord"": ""Mercury"",
                    ""awastha"": ""Mrityu"",
                    ""karakamsha"": ""Gnati"",
                    ""house"": 8,
                    ""type"": ""benefic"",
                    ""lord_of"": ""Eighth,First House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Venus.png""
                },
                {
                    ""name"": ""Mars"",
                    ""name_lan"": ""Mars"",
                    ""full_degree"": ""353.6450772"",
                    ""speed"": ""0.7072227"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""23:38:42"",
                    ""sign"": ""Pisces"",
                    ""sign_no"": 12,
                    ""rashi_lord"": ""Jupiter"",
                    ""nakshatra"": ""Revati"",
                    ""nakshatra_pada"": 3,
                    ""nakshatra_no"": 27,
                    ""nakshatra_lord"": ""Mercury"",
                    ""sub_lord"": ""Mars"",
                    ""awastha"": ""Kumar"",
                    ""karakamsha"": ""Maatra"",
                    ""house"": 6,
                    ""type"": ""malefic"",
                    ""lord_of"": ""Seventh,Second House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Mars.png""
                },
                {
                    ""name"": ""Jupiter"",
                    ""name_lan"": ""Jupiter"",
                    ""full_degree"": ""84.1045271"",
                    ""speed"": ""0.2208074"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""24:6:16"",
                    ""sign"": ""Gemini"",
                    ""sign_no"": 3,
                    ""rashi_lord"": ""Mercury"",
                    ""nakshatra"": ""Punarvasu"",
                    ""nakshatra_pada"": 2,
                    ""nakshatra_no"": 7,
                    ""nakshatra_lord"": ""Jupiter"",
                    ""sub_lord"": ""Mercury"",
                    ""awastha"": ""Mrityu"",
                    ""karakamsha"": ""Bhratra"",
                    ""house"": 9,
                    ""type"": ""malefic"",
                    ""lord_of"": ""Third,Sixth House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Jupiter.png""
                },
                {
                    ""name"": ""Saturn"",
                    ""name_lan"": ""Saturn"",
                    ""full_degree"": ""269.7474605"",
                    ""speed"": ""-0.0664860"",
                    ""is_retro"": ""true"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""29:44:50"",
                    ""sign"": ""Sagittarius"",
                    ""sign_no"": 9,
                    ""rashi_lord"": ""Jupiter"",
                    ""nakshatra"": ""Uttara Ashadha"",
                    ""nakshatra_pada"": 1,
                    ""nakshatra_no"": 21,
                    ""nakshatra_lord"": ""Sun"",
                    ""sub_lord"": ""Rahu"",
                    ""awastha"": ""Mrityu"",
                    ""karakamsha"": ""Atma"",
                    ""house"": 3,
                    ""type"": ""benefic"",
                    ""lord_of"": ""Fourth,Fifth House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Saturn.png""
                },
                {
                    ""name"": ""Uranus"",
                    ""name_lan"": ""Uranus"",
                    ""full_degree"": ""254.0847117"",
                    ""speed"": ""-0.0404188"",
                    ""is_retro"": ""true"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""14:5:4"",
                    ""sign"": ""Sagittarius"",
                    ""sign_no"": 9,
                    ""rashi_lord"": ""Jupiter"",
                    ""nakshatra"": ""Poorva Ashadha"",
                    ""nakshatra_pada"": 1,
                    ""nakshatra_no"": 20,
                    ""nakshatra_lord"": ""Venus"",
                    ""sub_lord"": ""Venus"",
                    ""awastha"": ""Yuva"",
                    ""karakamsha"": """",
                    ""house"": 3,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Uranus.png""
                },
                {
                    ""name"": ""Neptune"",
                    ""name_lan"": ""Neptune"",
                    ""full_degree"": ""259.7606058"",
                    ""speed"": ""-0.0264630"",
                    ""is_retro"": ""true"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""19:45:38"",
                    ""sign"": ""Sagittarius"",
                    ""sign_no"": 9,
                    ""rashi_lord"": ""Jupiter"",
                    ""nakshatra"": ""Poorva Ashadha"",
                    ""nakshatra_pada"": 2,
                    ""nakshatra_no"": 20,
                    ""nakshatra_lord"": ""Venus"",
                    ""sub_lord"": ""Rahu"",
                    ""awastha"": ""Vriddha"",
                    ""karakamsha"": """",
                    ""house"": 3,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Neptune.png""
                },
                {
                    ""name"": ""Pluto"",
                    ""name_lan"": ""Pluto"",
                    ""full_degree"": ""201.5108619"",
                    ""speed"": ""-0.0165056"",
                    ""is_retro"": ""true"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""21:30:39"",
                    ""sign"": ""Libra"",
                    ""sign_no"": 7,
                    ""rashi_lord"": ""Venus"",
                    ""nakshatra"": ""Vishakha"",
                    ""nakshatra_pada"": 1,
                    ""nakshatra_no"": 16,
                    ""nakshatra_lord"": ""Jupiter"",
                    ""sub_lord"": ""Jupiter"",
                    ""awastha"": ""Vriddha"",
                    ""karakamsha"": """",
                    ""house"": 1,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Pluto.png""
                },
                {
                    ""name"": ""Rahu"",
                    ""name_lan"": ""Rahu"",
                    ""full_degree"": ""285.5002821"",
                    ""speed"": ""-0.0529920"",
                    ""is_retro"": ""true"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""15:30:1"",
                    ""sign"": ""Capricorn"",
                    ""sign_no"": 10,
                    ""rashi_lord"": ""Saturn"",
                    ""nakshatra"": ""Shravan"",
                    ""nakshatra_pada"": 2,
                    ""nakshatra_no"": 22,
                    ""nakshatra_lord"": ""Moon"",
                    ""sub_lord"": ""Jupiter"",
                    ""awastha"": ""Yuva"",
                    ""karakamsha"": """",
                    ""house"": 4,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Rahu.png""
                },
                {
                    ""name"": ""Ketu"",
                    ""name_lan"": ""Ketu"",
                    ""full_degree"": ""105.50028"",
                    ""speed"": ""-0.0529920"",
                    ""is_retro"": ""true"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""15:30:1"",
                    ""sign"": ""Cancer"",
                    ""sign_no"": 4,
                    ""rashi_lord"": ""Moon"",
                    ""nakshatra"": ""Pushya"",
                    ""nakshatra_pada"": 4,
                    ""nakshatra_no"": 8,
                    ""nakshatra_lord"": ""Saturn"",
                    ""sub_lord"": ""Jupiter"",
                    ""awastha"": ""Yuva"",
                    ""karakamsha"": """",
                    ""house"": 10,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Ketu.png""
                },
                {
                    ""name"": ""Ascendant"",
                    ""name_lan"": ""Ascendant"",
                    ""full_degree"": ""186.4461639"",
                    ""speed"": ""312.1685558"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""6:26:46"",
                    ""sign"": ""Libra"",
                    ""sign_no"": 7,
                    ""rashi_lord"": ""Venus"",
                    ""nakshatra"": ""Chitra"",
                    ""nakshatra_pada"": 4,
                    ""nakshatra_no"": 14,
                    ""nakshatra_lord"": ""Mars"",
                    ""sub_lord"": ""Moon"",
                    ""awastha"": ""Kumar"",
                    ""karakamsha"": """",
                    ""house"": 1,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Ascendant.png""
                }
            ]
        },
        ""p2"": {
            ""date"": ""1992-08-15"",
            ""time"": ""09:45:00"",
            ""latitude"": 19.076,
            ""longitude"": 72.8777,
            ""timezone"": 5.5,
            ""planets"": [
                {
                    ""name"": ""Sun"",
                    ""name_lan"": ""Sun"",
                    ""full_degree"": ""118.8272727"",
                    ""speed"": ""0.9605447"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""28:49:38"",
                    ""sign"": ""Cancer"",
                    ""sign_no"": 4,
                    ""rashi_lord"": ""Moon"",
                    ""nakshatra"": ""Ashleysha"",
                    ""nakshatra_pada"": 4,
                    ""nakshatra_no"": 9,
                    ""nakshatra_lord"": ""Mercury"",
                    ""sub_lord"": ""Saturn"",
                    ""awastha"": ""Baal"",
                    ""karakamsha"": ""Atma"",
                    ""house"": 11,
                    ""type"": ""malefic"",
                    ""lord_of"": ""Twelfth House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Sun.png""
                },
                {
                    ""name"": ""Moon"",
                    ""name_lan"": ""Moon"",
                    ""full_degree"": ""317.8274825"",
                    ""speed"": ""11.9068816"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""17:49:38"",
                    ""sign"": ""Aquarius"",
                    ""sign_no"": 11,
                    ""rashi_lord"": ""Saturn"",
                    ""nakshatra"": ""Satabhisha"",
                    ""nakshatra_pada"": 4,
                    ""nakshatra_no"": 24,
                    ""nakshatra_lord"": ""Rahu"",
                    ""sub_lord"": ""Sun"",
                    ""awastha"": ""Yuva"",
                    ""karakamsha"": ""Putra"",
                    ""house"": 6,
                    ""type"": ""malefic"",
                    ""lord_of"": ""Eleventh House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Moon.png""
                },
                {
                    ""name"": ""Mercury"",
                    ""name_lan"": ""Mercury"",
                    ""full_degree"": ""102.4594295"",
                    ""speed"": ""0.2455948"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""12:27:33"",
                    ""sign"": ""Cancer"",
                    ""sign_no"": 4,
                    ""rashi_lord"": ""Moon"",
                    ""nakshatra"": ""Pushya"",
                    ""nakshatra_pada"": 3,
                    ""nakshatra_no"": 8,
                    ""nakshatra_lord"": ""Saturn"",
                    ""sub_lord"": ""Mars"",
                    ""awastha"": ""Yuva"",
                    ""karakamsha"": ""Dara"",
                    ""house"": 11,
                    ""type"": ""benefic"",
                    ""lord_of"": ""Tenth,First House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Mercury.png""
                },
                {
                    ""name"": ""Venus"",
                    ""name_lan"": ""Venus"",
                    ""full_degree"": ""135.9677535"",
                    ""speed"": ""1.2294696"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""15:58:3"",
                    ""sign"": ""Leo"",
                    ""sign_no"": 5,
                    ""rashi_lord"": ""Sun"",
                    ""nakshatra"": ""Purva Phalguni"",
                    ""nakshatra_pada"": 1,
                    ""nakshatra_no"": 11,
                    ""nakshatra_lord"": ""Venus"",
                    ""sub_lord"": ""Sun"",
                    ""awastha"": ""Yuva"",
                    ""karakamsha"": ""Gnati"",
                    ""house"": 12,
                    ""type"": ""benefic"",
                    ""lord_of"": ""Ninth,Second House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Venus.png""
                },
                {
                    ""name"": ""Mars"",
                    ""name_lan"": ""Mars"",
                    ""full_degree"": ""49.1069111"",
                    ""speed"": ""0.6445111"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""19:6:24"",
                    ""sign"": ""Taurus"",
                    ""sign_no"": 2,
                    ""rashi_lord"": ""Venus"",
                    ""nakshatra"": ""Rohini"",
                    ""nakshatra_pada"": 3,
                    ""nakshatra_no"": 4,
                    ""nakshatra_lord"": ""Moon"",
                    ""sub_lord"": ""Mercury"",
                    ""awastha"": ""Kumar"",
                    ""karakamsha"": ""Maatra"",
                    ""house"": 9,
                    ""type"": ""malefic"",
                    ""lord_of"": ""Eighth,Third House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Mars.png""
                },
                {
                    ""name"": ""Jupiter"",
                    ""name_lan"": ""Jupiter"",
                    ""full_degree"": ""144.2053904"",
                    ""speed"": ""0.2047836"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""24:12:19"",
                    ""sign"": ""Leo"",
                    ""sign_no"": 5,
                    ""rashi_lord"": ""Sun"",
                    ""nakshatra"": ""Purva Phalguni"",
                    ""nakshatra_pada"": 4,
                    ""nakshatra_no"": 11,
                    ""nakshatra_lord"": ""Venus"",
                    ""sub_lord"": ""Mercury"",
                    ""awastha"": ""Mrityu"",
                    ""karakamsha"": ""Amatya"",
                    ""house"": 12,
                    ""type"": ""neutral"",
                    ""lord_of"": ""Fourth,Seventh House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Jupiter.png""
                },
                {
                    ""name"": ""Saturn"",
                    ""name_lan"": ""Saturn"",
                    ""full_degree"": ""290.7993557"",
                    ""speed"": ""-0.0737215"",
                    ""is_retro"": ""true"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""20:47:57"",
                    ""sign"": ""Capricorn"",
                    ""sign_no"": 10,
                    ""rashi_lord"": ""Saturn"",
                    ""nakshatra"": ""Shravan"",
                    ""nakshatra_pada"": 4,
                    ""nakshatra_no"": 22,
                    ""nakshatra_lord"": ""Moon"",
                    ""sub_lord"": ""Venus"",
                    ""awastha"": ""Kumar"",
                    ""karakamsha"": ""Bhratra"",
                    ""house"": 5,
                    ""type"": ""benefic"",
                    ""lord_of"": ""Fifth,Sixth House"",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Saturn.png""
                },
                {
                    ""name"": ""Uranus"",
                    ""name_lan"": ""Uranus"",
                    ""full_degree"": ""260.8788312"",
                    ""speed"": ""-0.0288575"",
                    ""is_retro"": ""true"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""20:52:43"",
                    ""sign"": ""Sagittarius"",
                    ""sign_no"": 9,
                    ""rashi_lord"": ""Jupiter"",
                    ""nakshatra"": ""Poorva Ashadha"",
                    ""nakshatra_pada"": 3,
                    ""nakshatra_no"": 20,
                    ""nakshatra_lord"": ""Venus"",
                    ""sub_lord"": ""Jupiter"",
                    ""awastha"": ""Vriddha"",
                    ""karakamsha"": """",
                    ""house"": 4,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Uranus.png""
                },
                {
                    ""name"": ""Neptune"",
                    ""name_lan"": ""Neptune"",
                    ""full_degree"": ""262.9029228"",
                    ""speed"": ""-0.0205783"",
                    ""is_retro"": ""true"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""22:54:10"",
                    ""sign"": ""Sagittarius"",
                    ""sign_no"": 9,
                    ""rashi_lord"": ""Jupiter"",
                    ""nakshatra"": ""Poorva Ashadha"",
                    ""nakshatra_pada"": 3,
                    ""nakshatra_no"": 20,
                    ""nakshatra_lord"": ""Venus"",
                    ""sub_lord"": ""Saturn"",
                    ""awastha"": ""Vriddha"",
                    ""karakamsha"": """",
                    ""house"": 4,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Neptune.png""
                },
                {
                    ""name"": ""Pluto"",
                    ""name_lan"": ""Pluto"",
                    ""full_degree"": ""206.4555808"",
                    ""speed"": ""0.0086261"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""26:27:20"",
                    ""sign"": ""Libra"",
                    ""sign_no"": 7,
                    ""rashi_lord"": ""Venus"",
                    ""nakshatra"": ""Vishakha"",
                    ""nakshatra_pada"": 2,
                    ""nakshatra_no"": 16,
                    ""nakshatra_lord"": ""Jupiter"",
                    ""sub_lord"": ""Ketu"",
                    ""awastha"": ""Mrityu"",
                    ""karakamsha"": """",
                    ""house"": 2,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Pluto.png""
                },
                {
                    ""name"": ""Rahu"",
                    ""name_lan"": ""Rahu"",
                    ""full_degree"": ""244.0180180"",
                    ""speed"": ""-0.0529920"",
                    ""is_retro"": ""true"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""4:1:4"",
                    ""sign"": ""Sagittarius"",
                    ""sign_no"": 9,
                    ""rashi_lord"": ""Jupiter"",
                    ""nakshatra"": ""Moola"",
                    ""nakshatra_pada"": 2,
                    ""nakshatra_no"": 19,
                    ""nakshatra_lord"": ""Ketu"",
                    ""sub_lord"": ""Moon"",
                    ""awastha"": ""Baal"",
                    ""karakamsha"": """",
                    ""house"": 4,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Rahu.png""
                },
                {
                    ""name"": ""Ketu"",
                    ""name_lan"": ""Ketu"",
                    ""full_degree"": ""64.01802"",
                    ""speed"": ""-0.0529920"",
                    ""is_retro"": ""true"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""4:1:4"",
                    ""sign"": ""Gemini"",
                    ""sign_no"": 3,
                    ""rashi_lord"": ""Mercury"",
                    ""nakshatra"": ""Mrigashirsha"",
                    ""nakshatra_pada"": 4,
                    ""nakshatra_no"": 5,
                    ""nakshatra_lord"": ""Mars"",
                    ""sub_lord"": ""Venus"",
                    ""awastha"": ""Baal"",
                    ""karakamsha"": """",
                    ""house"": 10,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Ketu.png""
                },
                {
                    ""name"": ""Ascendant"",
                    ""name_lan"": ""Ascendant"",
                    ""full_degree"": ""166.1403274"",
                    ""speed"": ""341.1013150"",
                    ""is_retro"": ""false"",
                    ""is_combusted"": ""false"",
                    ""longitude"": ""16:8:25"",
                    ""sign"": ""Virgo"",
                    ""sign_no"": 6,
                    ""rashi_lord"": ""Mercury"",
                    ""nakshatra"": ""Hasta"",
                    ""nakshatra_pada"": 2,
                    ""nakshatra_no"": 13,
                    ""nakshatra_lord"": ""Moon"",
                    ""sub_lord"": ""Saturn"",
                    ""awastha"": ""Yuva"",
                    ""karakamsha"": """",
                    ""house"": 1,
                    ""type"": """",
                    ""lord_of"": """",
                    ""image"": ""https://divineapi.com/public/api-assets/assets/images/planets/Ascendant.png""
                }
            ]
        }
    }
}"; // Replace with the JSON you provided

        JObject root = JObject.Parse(sampleJson);
        JArray p1Planets = (JArray)root["data"]["p1"]["planets"];
        JArray p2Planets = (JArray)root["data"]["p2"]["planets"];

        string table = "<table><tr><th>Planet</th><th>Person 1</th><th>Person 2</th></tr>";

        // Loop through planets by index (assuming same order)
        int maxCount = Math.Max(p1Planets.Count, p2Planets.Count);
        for (int i = 0; i < maxCount; i++)
        {
            string planetName = "";
            string p1Details = "";
            string p2Details = "";

            if (i < p1Planets.Count)
            {
                planetName = p1Planets[i]["name"].ToString();
                p1Details = "Sign: " + p1Planets[i]["sign"] +
                            ", Nakshatra: " + p1Planets[i]["nakshatra"] +
                            ", House: " + p1Planets[i]["house"] +
                            ", Retro: " + p1Planets[i]["is_retro"] +
                            ", Combust: " + p1Planets[i]["is_combusted"];
            }

            if (i < p2Planets.Count)
            {
                if (planetName == "") planetName = p2Planets[i]["name"].ToString();
                p2Details = "Sign: " + p2Planets[i]["sign"] +
                            ", Nakshatra: " + p2Planets[i]["nakshatra"] +
                            ", House: " + p2Planets[i]["house"] +
                            ", Retro: " + p2Planets[i]["is_retro"] +
                            ", Combust: " + p2Planets[i]["is_combusted"];
            }

            table += "<tr><td>" + planetName + "</td><td>" + p1Details + "</td><td>" + p2Details + "</td></tr>";
        }

        table += "</table>";

        litPlanetsTable.Text = table;
    }
}